simulator_mainapp:
  ros__parameters:
    map: /home/wei/swarm_2d_ws/src/swarm_simulator/app/warehouse_01.png #必须指定绝对坐标
    # map: /home/wei/swarm_2d_ws/src/swarm_simulator/app/env_2.png
    names: [robot01, robot02, robot03, robot04]
    xs: [2.0, 5.0, 2.0, 5.0]
    ys: [2.0, 2.0, 6.0, 6.0]
    zs: [0.0, 0.0, 0.0, 0.0]